# config/meta.yml

meta_product_name: "teamind"
meta_title: "teamind - humanizing remote work"
meta_description: "Find out more about your teammates' personalities & work preferences"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
